import { NewCommentType, NewReplyType } from "../types/comment.types";
import { fetchWrapper } from "../utils/helpers";
const API_URL: string = "http://localhost:9000"; //mock API generated by JSON server from data/data.json file

/* Fetch Comments for Detail Page */
export async function fetchComments(feedbackId: string) {
  return fetchWrapper(`${API_URL}/comments?feedbackId=${feedbackId}`);
}

//Submit comment
export async function submitComment(
  commentData: NewCommentType | NewReplyType
) {
  return fetchWrapper(`${API_URL}/comments`, {
    method: "POST",
    body: JSON.stringify(commentData),
    headers: {
      "Content-Type": "application/json",
    },
  });
}
