import {
  NewFeedbackType,
  FeedbackType,
  StatusType,
} from "../types/feedback.types";
import { fetchWrapper } from "../utils/helpers";

const API_URL: string = "http://localhost:9000"; //mock API generated by JSON server from data/data.json file

interface EditedFeedbackType {
  title: string;
  description: string;
  category: string;
  status: string;
}

/* Fetch feedback list */
export async function fetchFeedbackList(
  pageContext: "feedbackBoard" | "developmentRoadmap"
) {
  const queryCondition =
    pageContext === "feedbackBoard" ? "" : "?status_ne=suggestion";

  const data: FeedbackType[] = await fetchWrapper(
    `${API_URL}/productRequests${queryCondition}`
  );

  const feedbackEntriesByStatus = data.reduce(
    (acc: Record<StatusType, FeedbackType[]>, curr: FeedbackType) => {
      const status = curr.status;

      acc[status].push(curr);
      return acc;
    },
    { suggestion: [], planned: [], "in-Progress": [], live: [] }
  );

  return feedbackEntriesByStatus;
}

/* Fetch feedback by id */
export async function fetchFeedbackById(feedbackId: string) {
  return fetchWrapper(`${API_URL}/productRequests/${feedbackId}`);
}

/* Submit new feedback */
export async function submitFeedback(feedback: NewFeedbackType) {
  try {
    const res = await fetchWrapper(`${API_URL}/productRequests`, {
      method: "POST",
      body: JSON.stringify(feedback),
      headers: {
        "Content-Type": "application/json",
      },
    });

    return { success: true };
  } catch (err) {
    console.error("Something went wrong inside SubmitFeedback", err);
    return { success: false };
  }
}

/* Edit feedback entry */
export async function editFeedback(
  feedbackId: string,
  editedFeedback: EditedFeedbackType
) {
  return fetchWrapper(`${API_URL}/productRequests/${feedbackId}`, {
    method: "PATCH",
    body: JSON.stringify(editedFeedback),
    headers: {
      "Content-Type": "application/json",
    },
  });
}

/* Delete feedback entry */
export async function deleteFeedback(feedbackId: string) {
  return fetchWrapper(`${API_URL}/productRequests/${feedbackId}`, {
    method: "DELETE",
  });
}

/* Update backend with current vote count after user's upvote/unvote actions */
export async function persistFeedbackVote(
  feedbackId: string,
  voteCount: number
) {
  try {
    const data = await fetchWrapper(
      `${API_URL}/productRequests/${feedbackId}`,
      {
        method: "PATCH",
        body: JSON.stringify({ upvotes: voteCount }),
        headers: {
          "Content-Type": "application/json",
        },
      }
    );

    if (!("upvotes" in data)) {
      throw Error();
    }

    return data.upvotes;
  } catch (err) {
    console.log("upvotes key not found", err);
    throw Error();
  }
}

/* Fetch user list */
export async function fetchUserList() {
  return fetchWrapper(`${API_URL}/userList`);
}

/* Update commentCount when a new comment/reply is added - currently working only incrementing commentCount
   TO DO: use the same function to decrement commentCount when a comment/reply is deleted
*/
export async function updateCommentCount(
  feedbackId: string,
  updatedCommentCount: number
) {
  return fetchWrapper(`${API_URL}/productRequests/${feedbackId}`, {
    method: "PATCH",
    body: JSON.stringify({ commentCount: updatedCommentCount }),
    headers: {
      "Content-Type": "application/json",
    },
  });
}
