import { NewFeedbackType, FeedbackType } from "../types/feedback.types";

const API_URL: string = "http://localhost:9000"; //mock API generated by JSON server from data/data.json file

/* Fetch Feedback List */
export async function fetchFeedbackList() {
  const res = await fetch(`${API_URL}/productRequests`);

  //throw an exeception if the  server responds with a 400 Bad Request error,
  // as fetch does not handle HTTP errors automatically
  if (!res.ok) throw Error("Failed getting Feedback Data");

  const data: FeedbackType[] = await res.json();
  return data;
}

/* Fetch feedback by id */
export async function fetchFeedbackById(feedbackId: string | undefined) {
  //type check against undefined above
  const res = await fetch(`${API_URL}/productRequests/${feedbackId}`);

  //throw an exeception if the server responds with a 400 Bad Request error,
  // as fetch does not handle HTTP errors automatically
  if (!res.ok) throw Error("Failed getting Feedback Data");

  const data = await res.json();
  return data;
}

/* Submit new feedback */
export async function submitFeedback(feedback: NewFeedbackType) {
  try {
    const res = await fetch(`${API_URL}/productRequests`, {
      method: "POST",
      body: JSON.stringify(feedback),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!res.ok) throw Error();
    const data = await res.json();

    return data;
  } catch {
    throw Error("Failed submitting Feedback");
  }
}

/* Edit feedback entry */
export async function editFeedback(
  feedbackId: string,
  editedFeedback: {
    title: string;
    description: string;
    category: string;
    status: string;
  }
) {
  try {
    const res = await fetch(`${API_URL}/productRequests/${feedbackId}`, {
      method: "PATCH",
      body: JSON.stringify(editedFeedback),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (!res.ok) throw Error();

    const data: FeedbackType = await res.json();
    return data;
  } catch {
    throw Error("Failed editing Feedback");
  }
}

/* Delete feedback entry */
export async function deleteFeedback(feedbackId: string) {
  try {
    const res = await fetch(`${API_URL}/productRequests/${feedbackId}`, {
      method: "DELETE",
    });

    if (res.ok) {
      console.log(
        `Feedback entry with id ${feedbackId} was deleted succesfully`
      );
    } else {
      throw Error();
    }
  } catch {
    throw Error(
      `There was an error deleting feedback entry with id ${feedbackId}`
    );
  }
}

/* Update backend with current vote count after user's upvote/unvote actions */
export async function persistFeedbackVote(
  feedbackId: string,
  voteCount: number
) {
  try {
    const res = await fetch(`${API_URL}/productRequests/${feedbackId}`, {
      method: "PATCH",
      body: JSON.stringify({ upvotes: voteCount }),
      headers: {
        "Content-Type": "application/json",
      },
    });

    if (res.ok) {
      console.log(
        `Feedback entry with id ${feedbackId} has been UPVOTED/UNVOTED`
      );
    } else {
      throw Error();
    }

    const data = await res.json();
    return data;
  } catch {
    throw Error(
      `There was an error UPVOTING/UNVOTING feedback entry with id ${feedbackId}`
    );
  }
}

/* Fetch user list */
export async function fetchUserList() {
  try {
    const res = await fetch(`${API_URL}/userList`);

    if (res.ok) {
      console.log("List of users has been retrieved successfully.");
    } else {
      throw Error();
    }

    return await res.json();
  } catch {
    throw Error(`There was an error retrieving list of users.`);
  }
}

/* Update commentCount when a new comment/reply is added - currently working only incrementing commentCount
   TO DO: use the same function to decrement commentCount when a comment/reply is deleted
*/
export async function updateCommentCount(
  feedbackId: string,
  updatedCommentCount: number
) {
  try {
    const res = await fetch(`${API_URL}/productRequests/${feedbackId}`, {
      method: "PATCH",
      body: JSON.stringify({ commentCount: updatedCommentCount }),
      headers: {
        "Content-Type": "application/json",
      },
    });
    if (res.ok) {
      console.log("Updating commentCount has been successful");
    } else {
      throw new Error();
    }

    await res.json();
  } catch {
    throw Error();
  }
}
